import Image from 'next/image'
import { Inter } from 'next/font/google'

import Header from '../components/Header.jsx'
import Head from 'next/head'
import TopCards from '@/components/TopCards.jsx'
import BarChart from '@/components/BarChart.jsx'
import RecentOrders from '@/components/RecentOrders.jsx'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>User Dashboard</title>
        <meta name='description' content='Generated by create next app'/>
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-gray-100 min-h-screen'>
        <Header page={'Dashboard'}/>
        <TopCards />
        <section className='grid p-4 md:grid-cols-3 grid-cols-1 gap-4'>
          <BarChart />
          <RecentOrders />
        </section>
        
      </main>
    </>
  )
}
